const express=require('express'); const path=require('path'); const {Pool}=require('pg');
const app=express(); app.use(express.json()); app.use(express.static(path.join(__dirname,'public')));
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false}):null;
const names=['Blue Devils','Bluecoats','Boston Crusaders','Carolina Crown','Santa Clara Vanguard','Phantom Regiment','The Cavaliers','Mandarins','Colts','Troopers','Blue Stars','Madison Scouts','Crossmen','Spirit of Atlanta','Pacific Crest','The Academy','Music City','Genesis','Seattle Cascades'];
const base=names.map((name,i)=>({id:i+1,name,cash:1500000-i*35000,management:78-i%9,staff:82-i%7,recruiting:80-i%11,design:84-i%10,morale:80,stability:82,score:68+Math.max(0,15-i)*.45,status:'ACTIVE'}));
let mem={year:2027,day:0,active:false,corps:base,history:[]};
async function init(){if(!pool)return; await pool.query(`CREATE TABLE IF NOT EXISTS sandbox_state(id int primary key,state jsonb not null)`); const r=await pool.query('SELECT state FROM sandbox_state WHERE id=1'); if(r.rows[0])mem=r.rows[0].state; else await save();}
async function save(){if(pool)await pool.query('INSERT INTO sandbox_state(id,state) VALUES(1,$1) ON CONFLICT(id) DO UPDATE SET state=$1',[JSON.stringify(mem)]);}
function step(){mem.day++; for(const c of mem.corps){if(c.status!=='ACTIVE')continue; const org=(c.management+c.staff+c.recruiting+c.design+c.morale+c.stability)/6; const noise=(Math.random()-.5)*1.15; const growth=.10+(org-50)/330+noise*.22; c.score=Math.max(45,Math.min(100,c.score+growth)); c.cash+=Math.round((c.management-62)*500-Math.max(0,80-c.stability)*850+(Math.random()-.52)*22000); c.morale=Math.max(0,Math.min(100,c.morale+(c.score>82?.25:-.05)+(Math.random()-.5))); c.stability=Math.max(0,Math.min(100,c.stability+(c.management-50)/300+(Math.random()-.5)*.5)); if(c.cash < -650000 || (c.stability<15&&c.management<20)){c.status='FOLDED';} c.score=+c.score.toFixed(3);} mem.history.push({year:mem.year,day:mem.day,scores:Object.fromEntries(mem.corps.map(c=>[c.id,c.score]))}); if(mem.day>=45)mem.active=false;}
app.get('/api/state',(q,s)=>s.json(mem));
app.post('/api/control/:id',async(q,s)=>{const c=mem.corps.find(x=>x.id==q.params.id); if(!c)return s.sendStatus(404); for(const k of ['cash','management','staff','recruiting','design','morale','stability','score']) if(q.body[k]!=null)c[k]=Number(q.body[k]); if(q.body.status)c.status=q.body.status; await save(); s.json(c)});
app.post('/api/step',async(q,s)=>{let n=Math.max(1,Math.min(20,Number(q.body.days)||1)); while(n--&&mem.day<45)step(); await save(); s.json(mem)});
app.post('/api/new-season',async(q,s)=>{mem.year++;mem.day=0;mem.active=false;mem.history=[];for(const c of mem.corps){if(c.status==='ACTIVE'){c.score=64+(c.design+c.staff+c.recruiting)/12+(Math.random()*3-1.5);c.score=Math.min(88,+c.score.toFixed(3));c.cash+=Math.round((c.management-50)*12000);}}await save();s.json(mem)});
app.post('/api/reset',async(q,s)=>{mem={year:2027,day:0,active:false,corps:JSON.parse(JSON.stringify(base)),history:[]};await save();s.json(mem)});
app.get('*',(q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));
init().then(()=>app.listen(process.env.PORT||3000,()=>console.log('DCI Sandbox running')));
